-- =====================================================
-- CLOUDMART DATABASE SCHEMA
-- =====================================================
--
-- Database:
--     cloudmart
--
-- Tables:
--     customers
--     products
--     orders
--     order_items
--     audit_logs
--
-- Customer registration:
--     lambda/customer/lambda_function.py
--
-- Important:
--     Customer tokens are generated by the Customer Lambda.
--     Only the SHA-256 token hash is stored in MySQL.
--     The original token is not stored in the database.
-- =====================================================


-- =====================================================
-- DATABASE
-- =====================================================

CREATE DATABASE IF NOT EXISTS cloudmart;

USE cloudmart;


-- =====================================================
-- CUSTOMERS TABLE
-- =====================================================

CREATE TABLE IF NOT EXISTS customers (

    customer_id VARCHAR(100) NOT NULL,

    name VARCHAR(100) NOT NULL,

    email VARCHAR(255) NOT NULL,

    phone VARCHAR(20) NOT NULL,

    /*
    SHA-256 hexadecimal hash contains 64 characters.

    The original token is never stored.

    The Customer Lambda generates the token and stores
    only its SHA-256 hash in this column.
    */

    auth_token_hash VARCHAR(64) NOT NULL,

    /*
    USER  = normal customer
    ADMIN = administrator
    */

    role VARCHAR(20) NOT NULL DEFAULT 'USER',

    created_at DATETIME NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at DATETIME NOT NULL
        DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (customer_id),

    /*
    Prevent duplicate email addresses.
    This automatically creates a unique index.
    */

    UNIQUE KEY uk_customers_email (email),

    /*
    Used by the Lambda Authorizer to find a customer
    using the SHA-256 hash of the received token.

    This automatically creates a unique index.
    It also prevents duplicate token hashes.
    */

    UNIQUE KEY uk_customers_auth_token (auth_token_hash),

    CONSTRAINT chk_customers_role
        CHECK (role IN ('USER', 'ADMIN'))

) ENGINE=InnoDB;


-- =====================================================
-- PRODUCTS TABLE
-- =====================================================

CREATE TABLE IF NOT EXISTS products (

    product_id INT NOT NULL AUTO_INCREMENT,

    name VARCHAR(255) NOT NULL,

    description TEXT,

    price DECIMAL(10,2) NOT NULL,

    stock_count INT NOT NULL DEFAULT 0,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (product_id),

    CONSTRAINT chk_products_status
        CHECK (status IN ('ACTIVE', 'INACTIVE')),

    CONSTRAINT chk_products_stock
        CHECK (stock_count >= 0),

    CONSTRAINT chk_products_price
        CHECK (price >= 0)

) ENGINE=InnoDB;


-- =====================================================
-- ORDERS TABLE
-- =====================================================

CREATE TABLE IF NOT EXISTS orders (

    order_id VARCHAR(50) NOT NULL,

    customer_id VARCHAR(100) NOT NULL,

    status VARCHAR(30) NOT NULL DEFAULT 'PROCESSING',

    total_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,

    created_at DATETIME NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at DATETIME NOT NULL
        DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (order_id),

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT chk_orders_total_amount
        CHECK (total_amount >= 0)

) ENGINE=InnoDB;


-- =====================================================
-- ORDER ITEMS TABLE
-- =====================================================

CREATE TABLE IF NOT EXISTS order_items (

    order_id VARCHAR(50) NOT NULL,

    product_id INT NOT NULL,

    quantity INT NOT NULL,

    price DECIMAL(10,2) NOT NULL,

    created_at DATETIME NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (order_id, product_id),

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT chk_order_items_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_order_items_price
        CHECK (price >= 0)

) ENGINE=InnoDB;


-- =====================================================
-- AUDIT LOGS TABLE
-- =====================================================

CREATE TABLE IF NOT EXISTS audit_logs (

    log_id BIGINT NOT NULL AUTO_INCREMENT,

    entity_type VARCHAR(30) NOT NULL,

    entity_id VARCHAR(100) NOT NULL,

    action VARCHAR(50) NOT NULL,

    old_value JSON NULL,

    new_value JSON NULL,

    performed_by VARCHAR(100) NULL,

    created_at DATETIME NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (log_id)

) ENGINE=InnoDB;


-- =====================================================
-- ADDITIONAL INDEXES
-- =====================================================
--
-- The following statements create normal indexes.
--
-- The customer email and auth_token_hash indexes are
-- already created automatically by their UNIQUE KEY
-- definitions above. Do not create duplicate indexes
-- for those columns.
-- =====================================================

CREATE INDEX idx_product_name
ON products(name);

CREATE INDEX idx_products_status
ON products(status);

CREATE INDEX idx_orders_customer
ON orders(customer_id);

CREATE INDEX idx_orders_status
ON orders(status);

CREATE INDEX idx_orders_created_at
ON orders(created_at);

CREATE INDEX idx_order_items_product
ON order_items(product_id);

CREATE INDEX idx_audit_entity
ON audit_logs(entity_type, entity_id);

CREATE INDEX idx_audit_action
ON audit_logs(action);

CREATE INDEX idx_audit_created_at
ON audit_logs(created_at);


-- =====================================================
-- SAMPLE PRODUCTS
-- =====================================================
--
-- These are optional sample products.
-- No customer tokens are inserted here.
-- =====================================================

INSERT INTO products
(
    product_id,
    name,
    description,
    price,
    stock_count,
    status
)
VALUES
(
    1,
    'Laptop',
    'Gaming Laptop',
    75000.00,
    10,
    'ACTIVE'
),
(
    2,
    'Mouse',
    'Wireless Mouse',
    1500.00,
    25,
    'ACTIVE'
),
(
    3,
    'Keyboard',
    'Mechanical Keyboard',
    3500.00,
    15,
    'ACTIVE'
)
ON DUPLICATE KEY UPDATE

    name = VALUES(name),

    description = VALUES(description),

    price = VALUES(price),

    stock_count = VALUES(stock_count),

    status = VALUES(status);


-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================

SELECT
    customer_id,
    name,
    email,
    phone,
    role,
    auth_token_hash,
    created_at,
    updated_at
FROM customers;


SELECT
    product_id,
    name,
    description,
    price,
    stock_count,
    status,
    created_at,
    updated_at
FROM products;


SELECT
    order_id,
    customer_id,
    status,
    total_amount,
    created_at,
    updated_at
FROM orders;


SELECT
    order_id,
    product_id,
    quantity,
    price,
    created_at
FROM order_items;


SELECT
    log_id,
    entity_type,
    entity_id,
    action,
    old_value,
    new_value,
    performed_by,
    created_at
FROM audit_logs;


-- =====================================================
-- INDEX VERIFICATION
-- =====================================================

SHOW INDEX FROM customers;


-- =====================================================
-- END OF CLOUDMART DATABASE SCHEMA
-- =====================================================