-- =====================================================
-- CLOUDMART DATABASE SCHEMA
-- =====================================================
--
-- Database:
--     cloudmart
--
-- Tables:
--     customers
--     products
--     orders
--     order_items
--     audit_logs
--
-- Customer registration:
--     lambda/customer/lambda_function.py
--
-- Important:
--     Customer tokens are generated by the Customer Lambda.
--     Only the SHA-256 token hash is stored in MySQL.
--     The original token is not stored in the database.
-- =====================================================

-- ============================================================
-- CLOUDMART DATABASE SCHEMA
-- Environment: dev
-- Database: cloudmart
-- ============================================================

CREATE DATABASE IF NOT EXISTS cloudmart;

USE cloudmart;



-- ============================================================
-- CUSTOMERS TABLE
-- ============================================================

CREATE TABLE customers (
    customer_id INT AUTO_INCREMENT PRIMARY KEY,

    name VARCHAR(100) NOT NULL,

    email VARCHAR(255) NOT NULL UNIQUE,

    phone VARCHAR(20) NOT NULL,

    auth_token_hash VARCHAR(64) NOT NULL,

    role VARCHAR(20) NOT NULL DEFAULT 'USER',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT chk_customer_role
        CHECK (role IN ('USER', 'ADMIN'))
);


-- ============================================================
-- CUSTOMER INDEXES
-- ============================================================

-- customer_id is automatically indexed because it is the
-- PRIMARY KEY.

-- This is a normal index, not a UNIQUE index.
CREATE INDEX idx_customers_auth_token
ON customers(auth_token_hash);

CREATE INDEX idx_customers_role
ON customers(role);


-- ============================================================
-- INSERT ADMIN CUSTOMER
-- ============================================================

INSERT INTO customers
(
    name,
    email,
    phone,
    auth_token_hash,
    role
)
VALUES
(
    'sultanAdmin',
    'sultanadmin123@admin.com',
    '9666666904',
    SHA2(CONCAT('sultanadmin123@admin.com', '9666666904'), 256),
    'ADMIN'
);


-- ============================================================
-- INSERT USER CUSTOMERS
-- ============================================================

INSERT INTO customers
(
    name,
    email,
    phone,
    auth_token_hash,
    role
)
VALUES
(
    'akshay',
    'uppu4678@gmail.com',
    '8891222333',
    SHA2(CONCAT('uppu4678@gmail.com', '8891222333'), 256),
    'USER'
),
(
    'rahul',
    'rahuldhoni07@gmail.com',
    '7791222344',
    SHA2(CONCAT('rahuldhoni07@gmail.com', '7791222344'), 256),
    'USER'
),
(
    'Karthik',
    'karthikpadi09@gmail.com',
    '9848909333',
    SHA2(CONCAT('karthikpadi09@gmail.com', '9848909333'), 256),
    'USER'
);


-- ============================================================
-- PRODUCTS TABLE
-- ============================================================

CREATE TABLE products (
    product_id INT AUTO_INCREMENT PRIMARY KEY,

    product_name VARCHAR(150) NOT NULL,

    description TEXT,

    category VARCHAR(100),

    price DECIMAL(10,2) NOT NULL,

    stock_quantity INT NOT NULL DEFAULT 0,

    low_stock_threshold INT NOT NULL DEFAULT 5,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT chk_product_price
        CHECK (price >= 0),

    CONSTRAINT chk_product_stock
        CHECK (stock_quantity >= 0),

    CONSTRAINT chk_product_threshold
        CHECK (low_stock_threshold >= 0)
);


-- ============================================================
-- PRODUCT INDEXES
-- ============================================================

CREATE INDEX idx_products_category
ON products(category);

CREATE INDEX idx_products_stock
ON products(stock_quantity);


-- ============================================================
-- SAMPLE PRODUCTS
-- ============================================================

INSERT INTO products
(
    product_name,
    description,
    category,
    price,
    stock_quantity,
    low_stock_threshold
)
VALUES
(
    'Laptop',
    'Business laptop',
    'Electronics',
    65000.00,
    20,
    5
),
(
    'Wireless Mouse',
    'Wireless optical mouse',
    'Accessories',
    1200.00,
    50,
    10
),
(
    'Mechanical Keyboard',
    'Mechanical RGB keyboard',
    'Accessories',
    4500.00,
    30,
    5
),
(
    'Monitor',
    '24 inch Full HD monitor',
    'Electronics',
    12000.00,
    15,
    5
),
(
    'USB-C Cable',
    'High-speed USB-C cable',
    'Accessories',
    800.00,
    100,
    20
);


-- ============================================================
-- ORDERS TABLE
-- ============================================================

CREATE TABLE orders (
    order_id INT AUTO_INCREMENT PRIMARY KEY,

    customer_id INT NOT NULL,

    total_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,

    order_status VARCHAR(30) NOT NULL DEFAULT 'PROCESSING',

    payment_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT chk_order_total
        CHECK (total_amount >= 0),

    CONSTRAINT chk_order_status
        CHECK (
            order_status IN (
                'PROCESSING',
                'CONFIRMED',
                'SHIPPED',
                'DELIVERED',
                'CANCELLED',
                'FAILED'
            )
        ),

    CONSTRAINT chk_payment_status
        CHECK (
            payment_status IN (
                'PENDING',
                'PAID',
                'FAILED',
                'REFUNDED'
            )
        )
);


-- ============================================================
-- ORDER INDEXES
-- ============================================================

CREATE INDEX idx_orders_customer_id
ON orders(customer_id);

CREATE INDEX idx_orders_status
ON orders(order_status);

CREATE INDEX idx_orders_created_at
ON orders(created_at);


-- ============================================================
-- ORDER ITEMS TABLE
-- ============================================================

CREATE TABLE order_items (
    order_item_id INT AUTO_INCREMENT PRIMARY KEY,

    order_id INT NOT NULL,

    product_id INT NOT NULL,

    quantity INT NOT NULL,

    unit_price DECIMAL(10,2) NOT NULL,

    subtotal DECIMAL(10,2) NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT chk_order_item_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_order_item_unit_price
        CHECK (unit_price >= 0),

    CONSTRAINT chk_order_item_subtotal
        CHECK (subtotal >= 0)
);


-- ============================================================
-- ORDER ITEM INDEXES
-- ============================================================

CREATE INDEX idx_order_items_order_id
ON order_items(order_id);

CREATE INDEX idx_order_items_product_id
ON order_items(product_id);


-- ============================================================
-- AUDIT LOGS TABLE
-- ============================================================

CREATE TABLE audit_logs (
    audit_id BIGINT AUTO_INCREMENT PRIMARY KEY,

    customer_id INT NULL,

    action VARCHAR(100) NOT NULL,

    entity_type VARCHAR(100),

    entity_id VARCHAR(100),

    details TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);


-- ============================================================
-- AUDIT LOG INDEXES
-- ============================================================

CREATE INDEX idx_audit_customer_id
ON audit_logs(customer_id);

CREATE INDEX idx_audit_action
ON audit_logs(action);

CREATE INDEX idx_audit_created_at
ON audit_logs(created_at);


-- ============================================================
-- VERIFICATION QUERIES
-- ============================================================

SELECT
    customer_id,
    name,
    email,
    phone,
    role,
    auth_token_hash
FROM customers;

SELECT
    product_id,
    product_name,
    category,
    price,
    stock_quantity,
    low_stock_threshold
FROM products;

SELECT
    TABLE_NAME,
    TABLE_ROWS
FROM information_schema.tables
WHERE table_schema = 'cloudmart';


-- ============================================================
-- TEST TOKENS
-- ============================================================

-- Admin token:
-- sultanadmin123@admin.com9666666904

-- Akshay token:
-- uppu4678@gmail.com8891222333

-- Rahul token:
-- rahuldhoni07@gmail.com7791222344

-- Karthik token:
-- karthikpadi09@gmail.com9848909333