AWSTemplateFormatVersion: '2010-09-09'

Description: CloudMart API Stack

Resources:

  #################################################
  # PRODUCT LAMBDA
  #################################################

  ProductLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: cloudmart-product
      Runtime: python3.13
      Handler: index.lambda_handler

      Role:
        Fn::ImportValue: cloudmart-product-role-arn

      Timeout: 15

      Environment:
        Variables:
          DB_HOST: cloudmart-data-stack-cloudmartdatabase-zjxdxen8ubpj.chyoy06e4uh2.ap-south-1.rds.amazonaws.com
          DB_NAME: cloudmart
          DB_USER: cloudmartadmin
          DB_PASSWORD: Akshay123
          DB_PORT: "3306"

      Code:
        ZipFile: |
          import json
          import os
          import pymysql

          DB_HOST = os.environ["DB_HOST"]
          DB_NAME = os.environ["DB_NAME"]
          DB_USER = os.environ["DB_USER"]
          DB_PASSWORD = os.environ["DB_PASSWORD"]
          DB_PORT = int(os.environ.get("DB_PORT", "3306"))

          def get_connection():
              return pymysql.connect(
                  host=DB_HOST,
                  user=DB_USER,
                  password=DB_PASSWORD,
                  database=DB_NAME,
                  port=DB_PORT,
                  connect_timeout=10,
                  cursorclass=pymysql.cursors.DictCursor
              )

          def lambda_handler(event, context):

              print("========== LAMBDA START ==========")
              print("Event:", json.dumps(event))

              try:

                  http_method = event.get("httpMethod", "GET")

                  print("HTTP Method:", http_method)

                  if http_method != "GET":
                      return {
                          "statusCode": 405,
                          "headers": {
                              "Content-Type": "application/json"
                          },
                          "body": json.dumps({
                              "message": "Method not allowed"
                          })
                      }

                  print("Connecting to RDS...")

                  connection = get_connection()

                  print("SUCCESS: Connected to RDS!")

                  with connection.cursor() as cursor:

                      print("Executing SELECT query...")

                      cursor.execute("SELECT * FROM products")

                      products = cursor.fetchall()

                      print("Products found:", len(products))

                  connection.close()

                  print("RDS connection closed")

                  return {
                      "statusCode": 200,
                      "headers": {
                          "Content-Type": "application/json",
                          "Access-Control-Allow-Origin": "*"
                      },
                      "body": json.dumps({
                          "message": "Products retrieved successfully",
                          "count": len(products),
                          "products": products
                      }, default=str)
                  }

              except Exception as e:

                  print("========== ERROR ==========")
                  print("ERROR TYPE:", type(e).__name__)
                  print("ERROR MESSAGE:", str(e))

                  return {
                      "statusCode": 500,
                      "headers": {
                          "Content-Type": "application/json",
                          "Access-Control-Allow-Origin": "*"
                      },
                      "body": json.dumps({
                          "message": "Failed to retrieve products",
                          "error": str(e)
                      })
                  }


  #################################################
  # API GATEWAY
  #################################################

  CloudMartApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: cloudmart-api

  #################################################
  # AUTHORIZER
  #################################################

  CloudMartAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: cloudmart-authorizer
      RestApiId: !Ref CloudMartApi
      Type: TOKEN
      IdentitySource: method.request.header.Authorization
      AuthorizerResultTtlInSeconds: 300

      AuthorizerUri:
        Fn::Sub:
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthorizerArn}/invocations
          - AuthorizerArn:
              Fn::ImportValue: cloudmart-authorizer-lambda-arn

  #################################################
  # /products
  #################################################

  ProductsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref CloudMartApi
      ParentId: !GetAtt CloudMartApi.RootResourceId
      PathPart: products

  ProductsGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref CloudMartApi
      ResourceId: !Ref ProductsResource
      HttpMethod: GET
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref CloudMartAuthorizer

      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
            - LambdaArn: !GetAtt ProductLambda.Arn

  ProductsPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref CloudMartApi
      ResourceId: !Ref ProductsResource
      HttpMethod: POST
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref CloudMartAuthorizer

      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
            - LambdaArn: !GetAtt ProductLambda.Arn

  #################################################
  # /products/{id}
  #################################################

  ProductIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref CloudMartApi
      ParentId: !Ref ProductsResource
      PathPart: "{id}"

  ProductIdGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref CloudMartApi
      ResourceId: !Ref ProductIdResource
      HttpMethod: GET
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref CloudMartAuthorizer

      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
            - LambdaArn: !GetAtt ProductLambda.Arn

  ProductIdPutMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref CloudMartApi
      ResourceId: !Ref ProductIdResource
      HttpMethod: PUT
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref CloudMartAuthorizer

      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
            - LambdaArn: !GetAtt ProductLambda.Arn

  ProductIdDeleteMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref CloudMartApi
      ResourceId: !Ref ProductIdResource
      HttpMethod: DELETE
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref CloudMartAuthorizer

      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
            - LambdaArn: !GetAtt ProductLambda.Arn

  #################################################
  # LAMBDA PERMISSION
  #################################################

  ProductLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ProductLambda
      Principal: apigateway.amazonaws.com

      SourceArn:
        !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${CloudMartApi}/*/*

  #################################################
  # API DEPLOYMENT
  #################################################

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment

    DependsOn:
      - ProductsGetMethod
      - ProductsPostMethod
      - ProductIdGetMethod
      - ProductIdPutMethod
      - ProductIdDeleteMethod

    Properties:
      RestApiId: !Ref CloudMartApi

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref CloudMartApi
      DeploymentId: !Ref ApiDeployment
      StageName: prod

Outputs:

  ApiId:
    Value: !Ref CloudMartApi
    Export:
      Name: cloudmart-api-id

  ApiInvokeUrl:
    Value: !Sub https://${CloudMartApi}.execute-api.${AWS::Region}.amazonaws.com/prod

  ProductLambdaArn:
    Value: !GetAtt ProductLambda.Arn
    Export:
      Name: cloudmart-product-lambda-arn