AWSTemplateFormatVersion: '2010-09-09'

Description: CloudMart API Stack

Parameters:

  CodeVersion:
    Type: String
    Description: Git commit SHA used to identify the Lambda deployment packages

  DBPassword:
    Type: String
    NoEcho: true
    Description: CloudMart RDS master password


Resources:

  #################################################
  # PRODUCT LAMBDA
  #################################################

  ProductLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: cloudmart-product
      Runtime: python3.13
      Handler: index.lambda_handler

      Role:
        Fn::ImportValue: cloudmart-product-role-arn

      Timeout: 15

      VpcConfig:
        SubnetIds:
          - Fn::ImportValue: cloudmart-private-subnet-id
          - Fn::ImportValue: cloudmart-private-subnet-2-id

        SecurityGroupIds:
          - Fn::ImportValue: cloudmart-lambda-sg

      Environment:
        Variables:
          DB_HOST:
            Fn::ImportValue: cloudmart-database-endpoint

          DB_NAME: cloudmart
          DB_USER: cloudmartadmin
          DB_PASSWORD: !Ref DBPassword
          DB_PORT: "3306"

      Code:
        S3Bucket: !Sub cloudmart-lambda-${AWS::AccountId}-${AWS::Region}
        S3Key: !Sub product/product-lambda-${CodeVersion}.zip


  #################################################
  # LOW STOCK SNS TOPIC
  #################################################

  LowStockTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: cloudmart-low-stock-alerts


  #################################################
  # LOW STOCK EMAIL SUBSCRIPTION
  #################################################

  LowStockEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref LowStockTopic
      Protocol: email
      Endpoint: uppu4678@gmail.com


  #################################################
  # LOW STOCK EVENTBRIDGE RULE
  #################################################

  InventoryLowStockRule:
    Type: AWS::Events::Rule
    Properties:
      Name: cloudmart-inventory-low-stock-rule

      Description: Send SNS alert when product stock is low

      EventPattern:
        source:
          - cloudmart.inventory

        detail-type:
          - InventoryChanged

        detail:
          stock_count:
            - numeric:
                - "<="
                - 5

      State: ENABLED

      Targets:
        - Arn: !Ref LowStockTopic
          Id: LowStockSNSTarget


  #################################################
  # LOW STOCK SNS TOPIC POLICY
  #################################################

  LowStockTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:

      Topics:
        - !Ref LowStockTopic

      PolicyDocument:
        Version: "2012-10-17"

        Statement:

          - Sid: AllowEventBridgePublish

            Effect: Allow

            Principal:
              Service: events.amazonaws.com

            Action:
              - sns:Publish

            Resource: !Ref LowStockTopic

            Condition:
              ArnEquals:
                aws:SourceArn:
                  !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/cloudmart-inventory-low-stock-rule


  #################################################
  # ORDER LAMBDA
  #################################################

  OrderLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: cloudmart-order
      Runtime: python3.13
      Handler: lambda_function.lambda_handler

      Role:
        Fn::ImportValue: cloudmart-order-role-arn

      Timeout: 15

      VpcConfig:
        SubnetIds:
          - Fn::ImportValue: cloudmart-private-subnet-id
          - Fn::ImportValue: cloudmart-private-subnet-2-id

        SecurityGroupIds:
          - Fn::ImportValue: cloudmart-lambda-sg

      Environment:
        Variables:
          DB_HOST:
            Fn::ImportValue: cloudmart-database-endpoint

          DB_NAME: cloudmart
          DB_USER: cloudmartadmin
          DB_PASSWORD: !Ref DBPassword
          DB_PORT: "3306"

      Code:
        S3Bucket: !Sub cloudmart-lambda-${AWS::AccountId}-${AWS::Region}

        S3Key: !Sub order/order-lambda-${CodeVersion}.zip


  #################################################
  # ORDER PROCESSOR LAMBDA
  #################################################

  OrderProcessorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: cloudmart-order-processor
      Runtime: python3.13
      Handler: lambda_function.lambda_handler

      Role:
        Fn::ImportValue: cloudmart-order-role-arn

      Timeout: 30

      VpcConfig:
        SubnetIds:
          - Fn::ImportValue: cloudmart-private-subnet-id
          - Fn::ImportValue: cloudmart-private-subnet-2-id

        SecurityGroupIds:
          - Fn::ImportValue: cloudmart-lambda-sg

      Environment:
        Variables:
          DB_HOST:
            Fn::ImportValue: cloudmart-database-endpoint

          DB_NAME: cloudmart
          DB_USER: cloudmartadmin
          DB_PASSWORD: !Ref DBPassword
          DB_PORT: "3306"

      Code:
        S3Bucket: !Sub cloudmart-lambda-${AWS::AccountId}-${AWS::Region}

        S3Key: !Sub order-processor/order-processor-${CodeVersion}.zip


  #################################################
  # ORDER CONFIRMATION SNS TOPIC
  #################################################

  OrderConfirmationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: cloudmart-order-confirmations


  #################################################
  # ORDER CONFIRMATION EMAIL
  #################################################

  OrderConfirmationEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref OrderConfirmationTopic
      Protocol: email
      Endpoint: uppu4678@gmail.com


  #################################################
  # ORDER CONFIRMATION EVENTBRIDGE RULE
  #################################################

  OrderConfirmedRule:
    Type: AWS::Events::Rule
    Properties:
      Name: cloudmart-order-confirmed-rule

      Description: Send email when an order is confirmed

      EventPattern:
        source:
          - cloudmart.orders

        detail-type:
          - OrderConfirmed

      State: ENABLED

      Targets:
        - Arn: !Ref OrderConfirmationTopic
          Id: OrderConfirmationSNSTarget


  #################################################
  # ORDER CONFIRMATION SNS POLICY
  #################################################

  OrderConfirmationTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:

      Topics:
        - !Ref OrderConfirmationTopic

      PolicyDocument:
        Version: "2012-10-17"

        Statement:

          - Sid: AllowEventBridgePublish

            Effect: Allow

            Principal:
              Service: events.amazonaws.com

            Action:
              - sns:Publish

            Resource: !Ref OrderConfirmationTopic

            Condition:
              ArnEquals:
                aws:SourceArn:
                  !GetAtt OrderConfirmedRule.Arn


  #################################################
  # ORDER PLACED EVENTBRIDGE RULE
  #################################################

  OrderPlacedRule:
    Type: AWS::Events::Rule
    Properties:
      Name: cloudmart-order-placed-rule

      Description: Process newly placed orders

      EventPattern:
        source:
          - cloudmart.orders

        detail-type:
          - OrderPlaced

      State: ENABLED

      Targets:
        - Arn: !GetAtt OrderProcessorLambda.Arn
          Id: OrderProcessorTarget


  #################################################
  # ORDER PROCESSOR EVENTBRIDGE PERMISSION
  #################################################

  OrderProcessorEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction

      FunctionName: !Ref OrderProcessorLambda

      Principal: events.amazonaws.com

      SourceArn:
        !GetAtt OrderPlacedRule.Arn


  #################################################
  # API GATEWAY
  #################################################

  CloudMartApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: cloudmart-api


  #################################################
  # AUTHORIZER
  #################################################

  CloudMartAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: cloudmart-authorizer

      RestApiId: !Ref CloudMartApi

      Type: TOKEN

      IdentitySource: method.request.header.Authorization

      AuthorizerResultTtlInSeconds: 0

      AuthorizerUri:
        Fn::Sub:
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthorizerArn}/invocations

          - AuthorizerArn:
              Fn::ImportValue: cloudmart-authorizer-lambda-arn


  #################################################
  # /products
  #################################################

  ProductsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref CloudMartApi
      ParentId: !GetAtt CloudMartApi.RootResourceId
      PathPart: products


  #################################################
  # GET /products
  #################################################

  ProductsGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref CloudMartApi
      ResourceId: !Ref ProductsResource

      HttpMethod: GET

      AuthorizationType: CUSTOM

      AuthorizerId: !Ref CloudMartAuthorizer

      Integration:
        Type: AWS_PROXY

        IntegrationHttpMethod: POST

        Uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations

            - LambdaArn: !GetAtt ProductLambda.Arn


  #################################################
  # POST /products
  #################################################

  ProductsPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref CloudMartApi
      ResourceId: !Ref ProductsResource

      HttpMethod: POST

      AuthorizationType: CUSTOM

      AuthorizerId: !Ref CloudMartAuthorizer

      Integration:
        Type: AWS_PROXY

        IntegrationHttpMethod: POST

        Uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations

            - LambdaArn: !GetAtt ProductLambda.Arn


  #################################################
  # /products/{id}
  #################################################

  ProductIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref CloudMartApi
      ParentId: !Ref ProductsResource
      PathPart: "{id}"


  #################################################
  # GET /products/{id}
  #################################################

  ProductIdGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref CloudMartApi
      ResourceId: !Ref ProductIdResource

      HttpMethod: GET

      AuthorizationType: CUSTOM

      AuthorizerId: !Ref CloudMartAuthorizer

      Integration:
        Type: AWS_PROXY

        IntegrationHttpMethod: POST

        Uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations

            - LambdaArn: !GetAtt ProductLambda.Arn


  #################################################
  # PUT /products/{id}
  #################################################

  ProductIdPutMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref CloudMartApi
      ResourceId: !Ref ProductIdResource

      HttpMethod: PUT

      AuthorizationType: CUSTOM

      AuthorizerId: !Ref CloudMartAuthorizer

      Integration:
        Type: AWS_PROXY

        IntegrationHttpMethod: POST

        Uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations

            - LambdaArn: !GetAtt ProductLambda.Arn


  #################################################
  # DELETE /products/{id}
  #################################################

  ProductIdDeleteMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref CloudMartApi
      ResourceId: !Ref ProductIdResource

      HttpMethod: DELETE

      AuthorizationType: CUSTOM

      AuthorizerId: !Ref CloudMartAuthorizer

      Integration:
        Type: AWS_PROXY

        IntegrationHttpMethod: POST

        Uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations

            - LambdaArn: !GetAtt ProductLambda.Arn


  #################################################
  # /orders
  #################################################

  OrdersResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref CloudMartApi
      ParentId: !GetAtt CloudMartApi.RootResourceId
      PathPart: orders


  #################################################
  # POST /orders
  #################################################

  OrdersPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref CloudMartApi
      ResourceId: !Ref OrdersResource

      HttpMethod: POST

      AuthorizationType: CUSTOM

      AuthorizerId: !Ref CloudMartAuthorizer

      Integration:
        Type: AWS_PROXY

        IntegrationHttpMethod: POST

        Uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations

            - LambdaArn: !GetAtt OrderLambda.Arn


  #################################################
  # GET /orders?customerId=X
  #################################################

  OrdersGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref CloudMartApi
      ResourceId: !Ref OrdersResource

      HttpMethod: GET

      AuthorizationType: CUSTOM

      AuthorizerId: !Ref CloudMartAuthorizer

      Integration:
        Type: AWS_PROXY

        IntegrationHttpMethod: POST

        Uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations

            - LambdaArn: !GetAtt OrderLambda.Arn


  #################################################
  # /orders/{id}
  #################################################

  OrderIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref CloudMartApi
      ParentId: !Ref OrdersResource
      PathPart: "{id}"


  #################################################
  # GET /orders/{id}
  #################################################

  OrderIdGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref CloudMartApi
      ResourceId: !Ref OrderIdResource

      HttpMethod: GET

      AuthorizationType: CUSTOM

      AuthorizerId: !Ref CloudMartAuthorizer

      Integration:
        Type: AWS_PROXY

        IntegrationHttpMethod: POST

        Uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations

            - LambdaArn: !GetAtt OrderLambda.Arn


  #################################################
  # AUTHORIZE AUTHORIZE LAMBDA
  #################################################

  AuthorizerLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction

      FunctionName:
        Fn::ImportValue: cloudmart-authorizer-lambda-arn

      Principal: apigateway.amazonaws.com

      SourceArn:
        !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${CloudMartApi}/*/*


  #################################################
  # PRODUCT LAMBDA PERMISSION
  #################################################

  ProductLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction

      FunctionName: !Ref ProductLambda

      Principal: apigateway.amazonaws.com

      SourceArn:
        !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${CloudMartApi}/*/*


  #################################################
  # ORDER LAMBDA PERMISSION
  #################################################

  OrderLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction

      FunctionName: !Ref OrderLambda

      Principal: apigateway.amazonaws.com

      SourceArn:
        !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${CloudMartApi}/*/*


  #################################################
  # API DEPLOYMENT
  #################################################

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment

    DependsOn:
      - ProductsGetMethod
      - ProductsPostMethod
      - ProductIdGetMethod
      - ProductIdPutMethod
      - ProductIdDeleteMethod

      - OrdersPostMethod
      - OrdersGetMethod
      - OrderIdGetMethod

    Properties:
      RestApiId: !Ref CloudMartApi


  #################################################
  # API STAGE
  #################################################

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref CloudMartApi
      DeploymentId: !Ref ApiDeployment
      StageName: prod


Outputs:

  #################################################
  # API ID
  #################################################

  ApiId:
    Value: !Ref CloudMartApi

    Export:
      Name: cloudmart-api-id


  #################################################
  # API INVOKE URL
  #################################################

  ApiInvokeUrl:
    Value: !Sub https://${CloudMartApi}.execute-api.${AWS::Region}.amazonaws.com/prod


  #################################################
  # PRODUCT LAMBDA ARN
  #################################################

  ProductLambdaArn:
    Value: !GetAtt ProductLambda.Arn

    Export:
      Name: cloudmart-product-lambda-arn


  #################################################
  # ORDER LAMBDA ARN
  #################################################

  OrderLambdaArn:
    Value: !GetAtt OrderLambda.Arn

    Export:
      Name: cloudmart-order-lambda-arn


  #################################################
  # ORDER PROCESSOR LAMBDA ARN
  #################################################

  OrderProcessorLambdaArn:
    Value: !GetAtt OrderProcessorLambda.Arn

    Export:
      Name: cloudmart-order-processor-lambda-arn


  #################################################
  # ORDER SNS TOPIC ARN
  #################################################

  OrderConfirmationTopicArn:
    Value: !Ref OrderConfirmationTopic

    Export:
      Name: cloudmart-order-confirmation-topic-arn