AWSTemplateFormatVersion: '2010-09-09'

Description: CloudMart Data Stack


# ================================================================
# PARAMETERS
# ================================================================

Parameters:

  DBName:
    Type: String
    Default: cloudmart
    Description: CloudMart RDS database name

  DBUsername:
    Type: String
    Default: cloudmartadmin
    Description: CloudMart RDS master username

  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: CloudMart RDS master password


# ================================================================
# RESOURCES
# ================================================================

Resources:


  # ==============================================================
  # RDS SUBNET GROUP
  # ==============================================================

  RdsSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup

    Properties:

      DBSubnetGroupDescription: CloudMart private RDS subnet group

      SubnetIds:

        - Fn::ImportValue:
            cloudmart-private-subnet-id

        - Fn::ImportValue:
            cloudmart-private-subnet-2-id

      Tags:

        - Key: Name
          Value: cloudmart-rds-subnet-group

        - Key: Application
          Value: CloudMart


  # ==============================================================
  # RDS MYSQL DATABASE
  #
  # Used for:
  #   Products
  #   Inventory
  #   Orders
  #   Order Items
  #   Product History
  # ==============================================================

  CloudMartDatabase:
    Type: AWS::RDS::DBInstance

    Properties:

      Engine: mysql

      EngineVersion: '8.0.46'

      DBInstanceClass: db.t3.micro

      AllocatedStorage: 20

      StorageType: gp3

      StorageEncrypted: true

      MultiAZ: false

      PubliclyAccessible: false

      DBName:
        !Ref DBName

      MasterUsername:
        !Ref DBUsername

      MasterUserPassword:
        !Ref DBPassword

      Port: 3306

      VPCSecurityGroups:

        - Fn::ImportValue:
            cloudmart-rds-sg

      DBSubnetGroupName:
        !Ref RdsSubnetGroup

      BackupRetentionPeriod: 0

      DeletionProtection: false

      CopyTagsToSnapshot: true

      AutoMinorVersionUpgrade: true

      Tags:

        - Key: Name
          Value: cloudmart-rds-mysql

        - Key: Application
          Value: CloudMart

        - Key: Service
          Value: RDS

        - Key: Environment
          Value: dev


  # ==============================================================
  # S3 BUCKET - REPORTS
  #
  # Report Lambda
  #       |
  #       v
  #      S3
  #       |
  #       v
  # EC2 Flask Dashboard
  # ==============================================================

  ReportsBucket:
    Type: AWS::S3::Bucket

    Properties:

      BucketName:
        !Sub cloudmart-reports-${AWS::AccountId}-${AWS::Region}

      BucketEncryption:

        ServerSideEncryptionConfiguration:

          - ServerSideEncryptionByDefault:

              SSEAlgorithm: AES256

      PublicAccessBlockConfiguration:

        BlockPublicAcls: true

        BlockPublicPolicy: true

        IgnorePublicAcls: true

        RestrictPublicBuckets: true

      VersioningConfiguration:

        Status: Enabled

      Tags:

        - Key: Name
          Value: cloudmart-reports

        - Key: Service
          Value: CloudMart

        - Key: DataType
          Value: Reports

        - Key: Environment
          Value: dev


  # ==============================================================
  # S3 BUCKET - LAMBDA DEPLOYMENT ARTIFACTS
  # ==============================================================

  LambdaArtifactsBucket:
    Type: AWS::S3::Bucket

    Properties:

      BucketName:
        !Sub cloudmart-lambda-${AWS::AccountId}-${AWS::Region}

      BucketEncryption:

        ServerSideEncryptionConfiguration:

          - ServerSideEncryptionByDefault:

              SSEAlgorithm: AES256

      PublicAccessBlockConfiguration:

        BlockPublicAcls: true

        BlockPublicPolicy: true

        IgnorePublicAcls: true

        RestrictPublicBuckets: true

      VersioningConfiguration:

        Status: Enabled

      Tags:

        - Key: Name
          Value: cloudmart-lambda-artifacts

        - Key: Service
          Value: CloudMart

        - Key: DataType
          Value: LambdaArtifacts

        - Key: Environment
          Value: dev


# ================================================================
# OUTPUTS
# ================================================================

Outputs:


  # ==============================================================
  # RDS DATABASE IDENTIFIER
  # ==============================================================

  DatabaseIdentifier:

    Description: RDS MySQL Database Identifier

    Value:
      !Ref CloudMartDatabase

    Export:
      Name: cloudmart-database-identifier


  # ==============================================================
  # RDS DATABASE RESOURCE ID
  # ==============================================================

  DatabaseResourceId:

    Description: RDS MySQL DB Resource ID

    Value:
      !GetAtt CloudMartDatabase.DbiResourceId

    Export:
      Name: cloudmart-database-resource-id


  # ==============================================================
  # RDS ENDPOINT
  # ==============================================================

  DatabaseEndpoint:

    Description: RDS MySQL Endpoint

    Value:
      !GetAtt CloudMartDatabase.Endpoint.Address

    Export:
      Name: cloudmart-database-endpoint


  # ==============================================================
  # RDS PORT
  # ==============================================================

  DatabasePort:

    Description: RDS MySQL Port

    Value:
      !GetAtt CloudMartDatabase.Endpoint.Port

    Export:
      Name: cloudmart-database-port


  # ==============================================================
  # DATABASE NAME
  # ==============================================================

  DatabaseName:

    Description: CloudMart RDS Database Name

    Value:
      !Ref DBName

    Export:
      Name: cloudmart-database-name


  # ==============================================================
  # DATABASE USERNAME
  # ==============================================================

  DatabaseUsername:

    Description: CloudMart RDS Username

    Value:
      !Ref DBUsername

    Export:
      Name: cloudmart-database-username


  # ==============================================================
  # RDS SUBNET GROUP
  # ==============================================================

  DatabaseSubnetGroup:

    Description: CloudMart RDS Subnet Group

    Value:
      !Ref RdsSubnetGroup

    Export:
      Name: cloudmart-database-subnet-group


  # ==============================================================
  # REPORTS S3 BUCKET
  # ==============================================================

  ReportsBucket:

    Description: S3 bucket used for CloudMart daily reports

    Value:
      !Ref ReportsBucket

    Export:
      Name: cloudmart-reports-bucket


  # ==============================================================
  # REPORTS S3 BUCKET ARN
  # ==============================================================

  ReportsBucketArn:

    Description: ARN of the CloudMart reports bucket

    Value:
      !GetAtt ReportsBucket.Arn

    Export:
      Name: cloudmart-reports-bucket-arn


  # ==============================================================
  # LAMBDA ARTIFACTS BUCKET
  # ==============================================================

  LambdaBucket:

    Description: S3 bucket used for Lambda deployment packages

    Value:
      !Ref LambdaArtifactsBucket

    Export:
      Name: cloudmart-lambda-bucket


  # ==============================================================
  # LAMBDA ARTIFACTS BUCKET ARN
  # ==============================================================

  LambdaBucketArn:

    Description: ARN of the CloudMart Lambda deployment bucket

    Value:
      !GetAtt LambdaArtifactsBucket.Arn

    Export:
      Name: cloudmart-lambda-bucket-arn