AWSTemplateFormatVersion: '2010-09-09'

Description: CloudMart Data Stack


# ================================================================
# PARAMETERS
# ================================================================

Parameters:

  DBName:
    Type: String
    Default: cloudmart
    Description: CloudMart RDS database name


  DBUsername:
    Type: String
    Default: cloudmartadmin
    Description: CloudMart RDS master username


  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: CloudMart RDS master password


  OrdersTableName:
    Type: String
    Default: cloudmart-orders
    Description: DynamoDB table for CloudMart orders


# ================================================================
# RESOURCES
# ================================================================

Resources:


  # ==============================================================
  # RDS SUBNET GROUP
  # ==============================================================

  RdsSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup

    Properties:

      DBSubnetGroupDescription: CloudMart private RDS subnet group

      SubnetIds:

        - Fn::ImportValue: cloudmart-private-subnet-id

        - Fn::ImportValue: cloudmart-private-subnet-2-id

      Tags:

        - Key: Name
          Value: cloudmart-rds-subnet-group

        - Key: Application
          Value: CloudMart


  # ==============================================================
  # RDS MYSQL DATABASE
  #
  # Used for:
  #   Products
  #   Inventory
  #
  # RDS remains private inside the VPC.
  # ==============================================================

  CloudMartDatabase:
    Type: AWS::RDS::DBInstance

    Properties:

      # ------------------------------------------------------------
      # DATABASE ENGINE
      # ------------------------------------------------------------

      Engine: mysql

      # IMPORTANT:
      # '8.0' is not accepted as an exact RDS engine version.
      # Use a supported MySQL 8.0 minor version.
      EngineVersion: '8.0.45'


      # ------------------------------------------------------------
      # INSTANCE
      # ------------------------------------------------------------

      DBInstanceClass: db.t3.micro

      AllocatedStorage: 20

      StorageType: gp3

      StorageEncrypted: true


      # ------------------------------------------------------------
      # AVAILABILITY
      # ------------------------------------------------------------

      MultiAZ: false

      PubliclyAccessible: false


      # ------------------------------------------------------------
      # DATABASE CONFIGURATION
      # ------------------------------------------------------------

      DBName: !Ref DBName

      MasterUsername: !Ref DBUsername

      MasterUserPassword: !Ref DBPassword

      Port: 3306


      # ------------------------------------------------------------
      # SECURITY GROUP
      # ------------------------------------------------------------

      VPCSecurityGroups:

        - Fn::ImportValue: cloudmart-rds-sg


      # ------------------------------------------------------------
      # PRIVATE SUBNET GROUP
      # ------------------------------------------------------------

      DBSubnetGroupName: !Ref RdsSubnetGroup


      # ------------------------------------------------------------
      # BACKUP
      # ------------------------------------------------------------

      BackupRetentionPeriod: 0

      DeletionProtection: false

      CopyTagsToSnapshot: true

      AutoMinorVersionUpgrade: true


      # ------------------------------------------------------------
      # TAGS
      # ------------------------------------------------------------

      Tags:

        - Key: Name
          Value: cloudmart-rds-mysql

        - Key: Application
          Value: CloudMart

        - Key: Service
          Value: RDS

        - Key: Environment
          Value: dev


  # ==============================================================
  # DYNAMODB ORDERS TABLE
  #
  # Partition Key:
  #   order_id
  #
  # GSI:
  #   customer_id-index
  #
  # Used for:
  #   POST /orders
  #   GET /orders/{orderId}
  #   GET orders by customer
  # ==============================================================

  OrdersTable:
    Type: AWS::DynamoDB::Table

    Properties:

      TableName: !Ref OrdersTableName

      # ------------------------------------------------------------
      # ON-DEMAND BILLING
      # ------------------------------------------------------------

      BillingMode: PAY_PER_REQUEST


      # ------------------------------------------------------------
      # ATTRIBUTES
      #
      # Only attributes used by keys need to be defined here.
      # ------------------------------------------------------------

      AttributeDefinitions:

        - AttributeName: order_id
          AttributeType: S

        - AttributeName: customer_id
          AttributeType: S


      # ------------------------------------------------------------
      # PRIMARY KEY
      # ------------------------------------------------------------

      KeySchema:

        - AttributeName: order_id
          KeyType: HASH


      # ------------------------------------------------------------
      # CUSTOMER ID GSI
      # ------------------------------------------------------------

      GlobalSecondaryIndexes:

        - IndexName: customer_id-index

          KeySchema:

            - AttributeName: customer_id
              KeyType: HASH

          Projection:
            ProjectionType: ALL


      # ------------------------------------------------------------
      # POINT-IN-TIME RECOVERY
      # ------------------------------------------------------------

      PointInTimeRecoverySpecification:

        PointInTimeRecoveryEnabled: true


      # ------------------------------------------------------------
      # SERVER-SIDE ENCRYPTION
      # ------------------------------------------------------------

      SSESpecification:

        SSEEnabled: true


      # ------------------------------------------------------------
      # TAGS
      # ------------------------------------------------------------

      Tags:

        - Key: Name
          Value: cloudmart-orders

        - Key: Service
          Value: CloudMart

        - Key: DataType
          Value: Orders

        - Key: Environment
          Value: dev


  # ==============================================================
  # S3 BUCKET - REPORTS
  #
  # Used by:
  #
  # Report Lambda
  #       |
  #       v
  #     S3
  #       |
  #       v
  # EC2 Flask Dashboard
  # ==============================================================

  ReportsBucket:
    Type: AWS::S3::Bucket

    Properties:

      BucketName:
        !Sub cloudmart-reports-${AWS::AccountId}-${AWS::Region}


      # ------------------------------------------------------------
      # ENCRYPTION
      # ------------------------------------------------------------

      BucketEncryption:

        ServerSideEncryptionConfiguration:

          - ServerSideEncryptionByDefault:

              SSEAlgorithm: AES256


      # ------------------------------------------------------------
      # PUBLIC ACCESS BLOCK
      # ------------------------------------------------------------

      PublicAccessBlockConfiguration:

        BlockPublicAcls: true

        BlockPublicPolicy: true

        IgnorePublicAcls: true

        RestrictPublicBuckets: true


      # ------------------------------------------------------------
      # VERSIONING
      # ------------------------------------------------------------

      VersioningConfiguration:

        Status: Enabled


      # ------------------------------------------------------------
      # TAGS
      # ------------------------------------------------------------

      Tags:

        - Key: Name
          Value: cloudmart-reports

        - Key: Service
          Value: CloudMart

        - Key: DataType
          Value: Reports

        - Key: Environment
          Value: dev


  # ==============================================================
  # S3 BUCKET - LAMBDA DEPLOYMENT ARTIFACTS
  #
  # GitHub Actions uploads:
  #
  # product/product-lambda-<commit>.zip
  # order/order-lambda-<commit>.zip
  # order-processor/order-processor-<commit>.zip
  # report/report-lambda-<commit>.zip
  #
  # Application Stack then reads these objects.
  # ==============================================================

  LambdaArtifactsBucket:
    Type: AWS::S3::Bucket

    Properties:

      BucketName:
        !Sub cloudmart-lambda-${AWS::AccountId}-${AWS::Region}


      # ------------------------------------------------------------
      # ENCRYPTION
      # ------------------------------------------------------------

      BucketEncryption:

        ServerSideEncryptionConfiguration:

          - ServerSideEncryptionByDefault:

              SSEAlgorithm: AES256


      # ------------------------------------------------------------
      # PUBLIC ACCESS BLOCK
      # ------------------------------------------------------------

      PublicAccessBlockConfiguration:

        BlockPublicAcls: true

        BlockPublicPolicy: true

        IgnorePublicAcls: true

        RestrictPublicBuckets: true


      # ------------------------------------------------------------
      # VERSIONING
      # ------------------------------------------------------------

      VersioningConfiguration:

        Status: Enabled


      # ------------------------------------------------------------
      # TAGS
      # ------------------------------------------------------------

      Tags:

        - Key: Name
          Value: cloudmart-lambda-artifacts

        - Key: Service
          Value: CloudMart

        - Key: DataType
          Value: LambdaArtifacts

        - Key: Environment
          Value: dev


# ================================================================
# OUTPUTS
# ================================================================

Outputs:


  # ==============================================================
  # RDS DATABASE IDENTIFIER
  # ==============================================================

  DatabaseIdentifier:

    Description: RDS MySQL Database Identifier

    Value:
      !Ref CloudMartDatabase

    Export:
      Name: cloudmart-database-identifier


  # ==============================================================
  # RDS ENDPOINT
  # ==============================================================

  DatabaseEndpoint:

    Description: RDS MySQL Endpoint

    Value:
      !GetAtt CloudMartDatabase.Endpoint.Address

    Export:
      Name: cloudmart-database-endpoint


  # ==============================================================
  # RDS PORT
  # ==============================================================

  DatabasePort:

    Description: RDS MySQL Port

    Value:
      !GetAtt CloudMartDatabase.Endpoint.Port

    Export:
      Name: cloudmart-database-port


  # ==============================================================
  # DATABASE NAME
  # ==============================================================

  DatabaseName:

    Description: CloudMart RDS Database Name

    Value:
      !Ref DBName

    Export:
      Name: cloudmart-database-name


  # ==============================================================
  # DATABASE USERNAME
  # ==============================================================

  DatabaseUsername:

    Description: CloudMart RDS Username

    Value:
      !Ref DBUsername

    Export:
      Name: cloudmart-database-username


  # ==============================================================
  # RDS SUBNET GROUP
  # ==============================================================

  DatabaseSubnetGroup:

    Description: CloudMart RDS Subnet Group

    Value:
      !Ref RdsSubnetGroup

    Export:
      Name: cloudmart-database-subnet-group


  # ==============================================================
  # DYNAMODB ORDERS TABLE NAME
  # ==============================================================

  OrdersTableName:

    Description: DynamoDB Orders Table Name

    Value:
      !Ref OrdersTable

    Export:
      Name: cloudmart-orders-table-name


  # ==============================================================
  # DYNAMODB ORDERS TABLE ARN
  # ==============================================================

  OrdersTableArn:

    Description: DynamoDB Orders Table ARN

    Value:
      !GetAtt OrdersTable.Arn

    Export:
      Name: cloudmart-orders-table-arn


  # ==============================================================
  # REPORTS S3 BUCKET
  # ==============================================================

  ReportsBucket:

    Description: S3 bucket used for CloudMart daily reports

    Value:
      !Ref ReportsBucket

    Export:
      Name: cloudmart-reports-bucket


  # ==============================================================
  # REPORTS S3 BUCKET ARN
  # ==============================================================

  ReportsBucketArn:

    Description: ARN of the CloudMart reports bucket

    Value:
      !GetAtt ReportsBucket.Arn

    Export:
      Name: cloudmart-reports-bucket-arn


  # ==============================================================
  # LAMBDA ARTIFACTS BUCKET
  # ==============================================================

  LambdaBucket:

    Description: S3 bucket used for Lambda deployment packages

    Value:
      !Ref LambdaArtifactsBucket

    Export:
      Name: cloudmart-lambda-bucket


  # ==============================================================
  # LAMBDA ARTIFACTS BUCKET ARN
  # ==============================================================

  LambdaBucketArn:

    Description: ARN of the Lambda deployment artifacts bucket

    Value:
      !GetAtt LambdaArtifactsBucket.Arn

    Export:
      Name: cloudmart-lambda-bucket-arn