      - name: Validate IAM Stack
        run: |
          aws cloudformation validate-template \
          --template-body file://cloudformation/iam-stack.yaml

      - name: Deploy IAM Stack
        run: |
          aws cloudformation deploy \
          --stack-name cloudmart-iam-stack \
          --template-file cloudformation/iam-stack.yaml \
          --capabilities CAPABILITY_NAMED_IAM

      - name: Check IAM Stack Status
        run: |
          aws cloudformation describe-stacks \
          --stack-name cloudmart-iam-stack